/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith('/_')) {
      return false;
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.

    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'), // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }

  self.addEventListener('fetch', (event) => {
    // You can use event.request to get information about the request that's being made.
    // You can use event.respondWith to create a custom response.
    event.respondWith(new Response('Hello from the service worker!'));
  });
});

// Any other custom service worker logic can go here.


// Use the StaleWhileRevalidate strategy for any requests that match this pattern
const matchCss = ({url}) => url.pathname.endsWith('.css');
const matchJs = ({url}) => url.pathname.endsWith('.js');
const matchPng = ({url}) => url.pathname.endsWith('.png');
const matchJpg = ({url}) => url.pathname.endsWith('.jpg');

const cssHandler = new StaleWhileRevalidate({
    cacheName: 'css-cache',
});
const jsHandler = new StaleWhileRevalidate({
    cacheName: 'js-cache',
});
const pngHandler = new StaleWhileRevalidate({
    cacheName: 'png-cache',
});
const jpgHandler = new StaleWhileRevalidate({
    cacheName: 'jpg-cache',
});

registerRoute(matchCss, cssHandler);
registerRoute(matchJs, jsHandler);
registerRoute(matchPng, pngHandler);
registerRoute(matchJpg, jpgHandler);

registerRoute(
  // Match image requests
  ({ request }) => request.destination === 'image',
  // Use the stale-while-revalidate strategy.
  new StaleWhileRevalidate({
    // Use a custom cache name.
    cacheName: 'images',
    plugins: [
      // Expire images after 7 days.
      new ExpirationPlugin({
        maxAgeSeconds: 7 * 24 * 60 * 60,
      }),
    ],
  })
);